config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "prompts#index"
  get '/users/:id/edit' => "users#index"
  resources :users
  resources :prompts do
    resources :chapters
  end
  get '/favorites' => 'favorites#index'
  resources :prompts do
    member do
      post 'add_favorite'
      delete 'remove_favorite'
    end
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  default_scope { order('created_at ASC') }
  belongs_to :prompt
  belongs_to :user
  validates_presence_of :body
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :prompt
  belongs_to :user
end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  has_many :chapters
  belongs_to :user
  validates_presence_of :title, :body
  has_many :favorites
  has_many :favorited_by, through: :favorites, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prompts
  has_many :chapters
  has_many :favorites
  has_many :favorite, through: :favorites, source: :prompt
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def new
    @prompt = Prompt.find(params[:prompt_id])
    @chapter = Chapter.new
  end
  def create
    @prompt = Prompt.find(params[:prompt_id])
    @chapter = @prompt.chapters.create(chapter_params.merge(user: current_user))
    redirect_to prompt_path(@prompt)
  end
  def edit
    @prompt = Prompt.find(params[:prompt_id])
    @chapter = Chapter.find(params[:id])
  end
  def update
    @prompt = Prompt.find(params[:prompt_id])
    @chapter = Chapter.find(params[:id])
    @chapter.update(chapter_params.merge(user:current_user))
    redirect_to prompt_path(@prompt)
  end
  def destroy
    @prompt = Prompt.find(params[:prompt_id])
    @chapter = Chapter.find(params[:id])
    @chapter.destroy
    redirect_to prompt_path(@prompt)
  end
  private
  def chapter_params
    params.require(:chapter).permit(:body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  def index
    @prompts = Prompt.all
  end
  def show
    @prompt = Prompt.find(params[:id])
  end
  def edit
    @prompt = Prompt.find(params[:id])
  end
  def new
    @prompt = Prompt.new
  end
  def create
    @prompt = Prompt.create!(prompt_params.merge(user: current_user))
    redirect_to prompt_path(@prompt)
  end
  def update
    @prompt = Prompt.find(params[:id])
    @prompt.update(prompt_params.merge(user: current_user))
    redirect_to prompt_path(@prompt)
  end
  def destroy
    @prompt = Prompt.find(params[:id])
    @prompt.favorites.destroy_all
    @prompt.destroy
    redirect_to prompts_path
  end
  def add_favorite
    @prompt = Prompt.find(params[:id])

    @prompt.favorites.create(user: current_user)
    redirect_to prompt_path(@prompt)
  end
  def remove_favorite
    @prompt = Prompt.find(params[:id])
    @prompt.favorites.destroy_all
    redirect_to prompt_path(@prompt)
  end
  private
  def prompt_params
    params.require(:prompt).permit(:title, :location, :time_period, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def edit
    @users = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params.merge(user: current_user))
    redirect_to user_path(@user)
  end
  private
  def user_params
    params.require(:user).permit(:username, :favorite_genre, :favorite_books, :about_me)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/_form.html.erb
<%= form_for [@prompt, @chapter] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/chapters/edit.html.erb
<h2>Edit Chapter</h2>

<%= render "form" %>

app/views/chapters/new.html.erb
<h2>New Chapter</h2>

<%= render "form" %>

app/views/favorites/index.html.erb
<h2>Flagged Prompts</h2>
  <ul>
    <% @favorites.each do |favorite| %>
      <div class = "favorite">
        <h4><%= link_to favorite.prompt.title, prompt_path(favorite.prompt) %></h4>
        <time>Created by <%= favorite.prompt.user.email %> on <%= favorite.prompt.created_at  %></time>
        <h5><%= favorite.prompt.body %></h5>
      </div>
      <br>__________________________________</br>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imprevise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
  <h1 class= 'img_logo'><%= link_to "ImpRevise", root_path %></h1>
  <h2 class= 'navbar'>
  <<%= link_to 'Prompts', prompts_path %>
  <% if current_user %>
    <<%= link_to 'Profile', user_path(current_user) %>
    <<%= link_to 'Flagged Prompts', '/favorites' %>
    <<%= link_to 'Penned Prompts', '/users' %>
    <<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
  <% else %>
    <<%= link_to 'Signup', new_user_registration_path %>
    <<%= link_to 'Login', new_user_session_path %>
  </h2>
  </header>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/prompts/_form.html.erb
<%= form_for @prompt do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :time_period %>
  <%= f.text_field :time_period %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/prompts/edit.html.erb
<h2>Edit Prompt</h2>
<%= render "form" %>

app/views/prompts/index.html.erb
<% if current_user %>
  <h2>Prompts <a href="/prompts/new">(create a new prompt)</a></h2>
<% end %>
  <ul>
    <% @prompts.each do |prompt| %>
      <div class = "prompt">
        <h4><%= link_to prompt.title, prompt_path(prompt) %></h4>
        <time>Created by <%= prompt.user.email %> on <%= prompt.created_at %></time>
        <h5><%= prompt.body %></h5>
      </div>
      <br>__________________________________</br>
    <% end %>
  </ul>

app/views/prompts/new.html.erb
<h2>New Prompt</h2>

<%= render "form" %>

app/views/prompts/show.html.erb
<article>
  <h2><%= @prompt.title %></h2>
  <% if @prompt.favorites.length > 0 %>
    <%= link_to "&#9873;".html_safe, remove_favorite_prompt_path(@prompt), method: :delete, class: "fav" %>
  <% else %>
    <%= link_to "&#9873;".html_safe, add_favorite_prompt_path(@prompt), method: :post, class: "no-fav" %>
  <% end %>
    <time>Created by <%= @prompt.user.email %> on <%= @prompt.created_at %></time>
      <p><%= "Time period:"%>  <%= @prompt.time_period %></p>
      <p><%= "Location:"%>  <%= @prompt.location %></p>
      <p><%= @prompt.body %></p>
    <% if current_user == @prompt.user %>
      [<%= link_to "Edit", edit_prompt_path(@prompt) %>] [<%= link_to "Delete", prompt_path(@prompt), method: :delete %>]
    <% end %>
  <div class='chapters'>
  <h3>Chapters</h3>
  <br>________________________</br>
  <% @prompt.chapters.each do |chapter| %>
    <time>Created by <%= chapter.user.email %> on <%= chapter.created_at %></time>
    <p><%= chapter.body %></p>
  <% if current_user == chapter.user %>
  	[<%= link_to "Edit", edit_prompt_chapter_path(@prompt, chapter) %>] [<%= link_to "Delete", prompt_chapter_path(@prompt, chapter), method: :delete %>]
  <% end %>
    <br>________________________</br>
  <% end %>
  <% if current_user %>
    <%= link_to "Add new chapter", new_prompt_chapter_path(@prompt) %>
  <% end %>
</article>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :favorite_genre %>
  <%= f.text_field :favorite_genre %>
  <%= f.label :favorite_books %>
  <%= f.text_field :favorite_books %>
  <%= f.label :about_me %>
  <%= f.text_area :about_me %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= render "form" %>

app/views/users/index.html.erb
<h2>Penned Prompts</h2>
  <ul>
    <% @users.each do |user| %>
      <h4><%= link_to current_user.prompts, prompts_path(current_user.prompts) %></h4>
      <h5><%= current_user.prompts %></h5>
    <% end %>
  </ul>

app/views/users/show.html.erb
<h2><%= current_user.email %>'s profile</h2>